# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestErroralgestionarelperfildeusuario():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_erroralgestionarelperfildeusuario(self):
    self.driver.get("https://demowebshop.tricentis.com/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "Email").send_keys("santiago97@hotmail.com")
    self.driver.find_element(By.ID, "Password").click()
    self.driver.find_element(By.ID, "Password").send_keys("qwertyuiop")
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    self.driver.find_element(By.LINK_TEXT, "Santiago97@hotmail.com").click()
    self.driver.find_element(By.ID, "Email").click()
    self.driver.find_element(By.ID, "Email").send_keys("Santiago97")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset").click()
    self.driver.find_element(By.NAME, "save-info-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".field-validation-error > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    self.driver.close()
  
