# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarproductosalcarritoyfinalizarcompra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarproductosalcarritoyfinalizarcompra(self):
    self.driver.get("https://demowebshop.tricentis.com/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "Email").send_keys("santiago97@hotmail.com")
    self.driver.find_element(By.ID, "Password").click()
    self.driver.find_element(By.ID, "Password").send_keys("qwertyuiop")
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    self.driver.find_element(By.ID, "small-searchterms").click()
    self.driver.find_element(By.ID, "small-searchterms").send_keys("laptop")
    self.driver.find_element(By.ID, "small-searchterms").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".product-item img").click()
    self.driver.find_element(By.ID, "add-to-cart-button-31").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ico-cart > .cart-label").click()
    self.driver.find_element(By.ID, "CountryId").click()
    dropdown = self.driver.find_element(By.ID, "CountryId")
    dropdown.find_element(By.XPATH, "//option[. = 'Colombia']").click()
    self.driver.find_element(By.ID, "termsofservice").click()
    self.driver.find_element(By.ID, "checkout").click()
    self.driver.find_element(By.ID, "billing-address-select").click()
    dropdown = self.driver.find_element(By.ID, "billing-address-select")
    dropdown.find_element(By.XPATH, "//option[. = 'New Address']").click()
    self.driver.find_element(By.ID, "BillingNewAddress_CountryId").click()
    dropdown = self.driver.find_element(By.ID, "BillingNewAddress_CountryId")
    dropdown.find_element(By.XPATH, "//option[. = 'Colombia']").click()
    self.driver.find_element(By.ID, "BillingNewAddress_City").click()
    self.driver.find_element(By.ID, "BillingNewAddress_City").send_keys("Barranquilla")
    self.driver.find_element(By.ID, "BillingNewAddress_Address1").click()
    self.driver.find_element(By.ID, "BillingNewAddress_Address1").send_keys("calle50#13-26")
    self.driver.find_element(By.ID, "BillingNewAddress_Address2").click()
    self.driver.find_element(By.ID, "BillingNewAddress_Address2").send_keys("Calle45F#20-31")
    self.driver.find_element(By.ID, "BillingNewAddress_ZipPostalCode").click()
    self.driver.find_element(By.ID, "BillingNewAddress_ZipPostalCode").send_keys("080011")
    self.driver.find_element(By.ID, "BillingNewAddress_PhoneNumber").click()
    self.driver.find_element(By.ID, "BillingNewAddress_PhoneNumber").send_keys("3008248335")
    self.driver.find_element(By.CSS_SELECTOR, ".new-address-next-step-button:nth-child(1)").click()
    self.driver.find_element(By.ID, "PickUpInStore").click()
    self.driver.find_element(By.CSS_SELECTOR, ".new-address-next-step-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method-next-step-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-info-next-step-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm-order-next-step-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-2").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    self.driver.close()
  
