# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBsquedayseleccindeproducto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bsquedayseleccindeproducto(self):
    self.driver.get("https://demowebshop.tricentis.com/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.ID, "small-searchterms").click()
    self.driver.find_element(By.ID, "small-searchterms").send_keys("laptop")
    self.driver.find_element(By.CSS_SELECTOR, ".search-box-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".picture img").click()
    self.driver.find_element(By.ID, "main-product-img-31").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "14.1-inch Laptop"
    assert self.driver.find_element(By.CSS_SELECTOR, "p").text == "Optimize your mobility with a BrightView 14.1-inch display that has the same viewable area as a 15.4-inch screen--in a notebook that weighs a pound less. Encouraging more direct interaction, the backlit media control panel responds to the touch or sweep of a finger. Control settings for audio and video playback from up to 10 feet away with the included HP remote, then store it conveniently in the PC card slot."
    self.driver.close()
  
